name: CI

on:
  push:
    branches: [develop, feature/sdl]
  pull_request:
    branches: [develop]

jobs:
  trivy-scan:
    uses: h4b-dev/n1-gh-reusable-workflows/.github/workflows/trivy-nodejs-bun-scan-workflow.yml@main
    with:
      node-version: "18"
      scan-path: "."

  sonarcloud-scan:
    uses: ./.github/workflows/sonarcloud-nodejs-bun-scan-workflow.yml
    with:
      sonar-project-key: "h4b-dev_n1-vgs-components"
      sonar-organization: "n1co"
      env-name: "n1-ci"
      node-version: "18"
      build-path: "."
    secrets: inherit
