name: CI
on:
  push:
    branches: [fix/ci-workflow]
  pull_request:
    branches: [develop]

jobs:
  trivy-scan:
    uses: h4b-dev/n1-gh-reusable-workflows/.github/workflows/trivy-nodejs-bun-scan-workflow.yml@main
    with:
      node-version: "18"
      scan-path: "."
